language: php

branches:
    only:
        - master

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
    - composer install --prefer-dist -n
    - ./bin/setup_test_environment.sh

    # This part is for making selenium work
    # Notice that you can also use PhantomJS
    - sh -e /etc/init.d/xvfb start && export DISPLAY=:99 && wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
    - java -jar selenium-server-standalone-2.42.2.jar > /dev/null &
    - sleep 5

    - php app/console ser:run &

notifications:
    # email:
    #     - developer@example.com

script:
    - bin/phpspec run
    - bin/behat --no-snippets --verbose
