language: php

php:
  - 5.4
  - 5.5

before_script:
    - composer install -n
    - ./bin/setup_test_environment.sh

    # This part is for making selenium work
    # Notice that you can also use PhantomJS
    - sh -e /etc/init.d/xvfb start && export DISPLAY=:99 && wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
    - java -jar selenium-server-standalone-2.37.0.jar > /dev/null &
    - sleep 5

    - php app/console ser:run &

notifications:
    # email:
    #     - developer@example.com

script:
    - bin/phpspec run
    - bin/behat --no-snippets --verbose
