version: '3'

services:
    db:
        image: mariadb:10.3.1
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nekowiki
            MYSQL_USER: user
            MYSQL_PASSWORD: userpass
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=db
            - PMA_USER=user
            - PMA_PASSWORD=userpass
        ports:
            - ${PMA_PORT}:80
        depends_on:
            - db
    php:
        build: docker/php
        env_file:
          - .env
        volumes:
            - .:/var/www/

    nginx:
        image: nginx:1.13.3
        ports:
            - ${HTTPD_PORT}:80
        volumes:
            - .:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
            - ./app/logs/nginx:/var/log/nginx
        depends_on:
            - php
