parameters:
    neko_wiki.form.search.class:                 Nekland\NekoWiki\Form\SearchType
    neko_wiki.form.registration.class:           Nekland\NekoWiki\Form\RegistrationType
    neko_wiki.form.page.class:                   Nekland\NekoWiki\Form\PageType
    neko_wiki.form.basic.text_translation.class: Nekland\NekoWiki\Form\Basic\TextTranslatableType
    neko_wiki.form.page_translation.class:       Nekland\NekoWiki\Form\PageTranslationType

services:
    neko_wiki.form.registration:
        class: %neko_wiki.form.registration.class%
        tags:
            - { name: form.type, alias: neko_wiki_registration }

    neko_wiki.form.search:
        class: %neko_wiki.form.search.class%
        tags:
            - { name: form.type, alias: neko_wiki_search }

    neko_wiki.form.page:
        class: %neko_wiki.form.page.class%
        tags:
            - { name: form.type, alias: neko_wiki_page }

    neko_wiki.form.basic.text_translation:
        class: %neko_wiki.form.basic.text_translation.class%
        tags:
            - { name: form.type, alias: text_translatable }

    neko_wiki.form.page_translation:
        class: %neko_wiki.form.page_translation.class%
        tags:
            - { name: form.type, alias: neko_wiki_page_translation }

    neko_wiki.form.basic.page_translation_collection:
        class: Nekland\NekoWiki\Form\Basic\PageTranslationCollectionType
        tags:
            - { name: form.type, alias: neko_wiki_page_translation_collection }
