parameters:
    neko_wiki.form.search.class:                 App\Form\SearchType
    neko_wiki.form.registration.class:           App\Form\RegistrationType
    neko_wiki.form.page.class:                   App\Form\PageType
    neko_wiki.form.basic.text_translation.class: App\Form\Basic\TextTranslatableType

services:
    neko_wiki.form.registration:
        class: %neko_wiki.form.registration.class%
        tags:
            - { name: form.type, alias: neko_wiki_registration }

    neko_wiki.form.search:
        class: %neko_wiki.form.search.class%
        tags:
            - { name: form.type, alias: neko_wiki_search }

    neko_wiki.form.page:
        class: %neko_wiki.form.page.class%
        tags:
            - { name: form.type, alias: neko_wiki_page }

    neko_wiki.form.basic.text_translation:
        class: %neko_wiki.form.basic.text_translation.class%
        tags:
            - { name: form.type, alias: text_translatable }
