parameters:
    neko_wiki.provider.page.class:     App\Provider\PageProvider
    neko_wiki.provider.wiki_parameter.class: App\Provider\WikiParameterProvider

services:
    neko_wiki.provider.page:
        class: %neko_wiki.provider.page.class%
        arguments: [ @doctrine.orm.default_entity_manager ]

    neko_wiki.provider.wiki_parameter:
        class: %neko_wiki.provider.wiki_parameter.class%

