homepage:
    path: /
    defaults:
        _controller: 'NekoWiki:Home:language'

neko_wiki_page:
    prefix: /
    resource: 'routing/page.yml'

neko_wiki_user:
    prefix: /
    resource: 'routing/user.yml'

neko_wiki_global:
    prefix: /
    resource: 'routing/global.yml'
