App\Entity\User\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        username:
            - NotBlank: ~
            - Length: { min: 2 }
        email:
            - Email: ~
            - NotBlank: ~
        password:
            - Length: { min: 4 }

App\Entity\PageTranslation:
    properties:
        title:
            - NotBlank: ~
            - Length: { min: 3 }
        content:
            - NotBlank: ~
            - Length: { min: 100 }
